### ISSUE TITLE
GetAllTapas

### ISSUE THREAD

**Issue by JLDEMIGUEL** [dDevTech/tapas-top-backend#30]
Crear en MyUserResource una ruta que reciba un id de usuario y devuelva una lista con todas las  tapas añadidas por el usuario

**Comment by edlv2001** [comment]
test1:
![image](https://user-images.githubusercontent.com/79944367/230731385-c5bf8de5-f95b-49c8-83c8-354f28261f31.png)

test2:
![image](https://user-images.githubusercontent.com/79944367/230731394-d45ff4a6-56c7-4cea-97d5-f0a2a22a97f7.png)

test3:
![image](https://user-images.githubusercontent.com/79944367/230731404-4ce8a24e-47bb-4403-b34a-88355381149f.png)
