### ISSUE TITLE
GetAllRestaurants

### ISSUE THREAD

**Issue by JLDEMIGUEL** [dDevTech/tapas-top-backend#31]
Crear en MyUserResource una ruta que reciba un id de usuario y devuelva una lista con todos los restaurantes añadidos por el usuario

**Comment by edlv2001** [comment]
test1:
![image](https://user-images.githubusercontent.com/79944367/230731029-0d278df9-f4b8-425d-8698-c9c3ff41469f.png)

test2:
![image](https://user-images.githubusercontent.com/79944367/230731051-c1c00816-10ac-4aed-9d83-7a8ad6c88527.png)

test3:
![image](https://user-images.githubusercontent.com/79944367/230731057-d287ec75-b344-4833-b116-598cdd1d410c.png)
