### ISSUE TITLE
Añadir rutas basicas Tapa

### ISSUE THREAD

**Issue by JLDEMIGUEL** [dDevTech/tapas-top-backend#34]
Añadir a TapaResource las rutas para:

- findAll
- findById
- save
- deleteById

Usando los métodos ya creados en TapaService

**Comment by edlv2001** [comment]
findById:
![image](https://user-images.githubusercontent.com/79944367/230725245-1a98a915-c419-49d2-a222-aad04fd5e3bd.png)

findAll:
![image](https://user-images.githubusercontent.com/79944367/230725257-94b8cae3-b081-4109-837f-0778b3ec8da6.png)

createTapa:
![image](https://user-images.githubusercontent.com/79944367/230725275-a753d554-26d1-4d43-89e0-6c253fa4ec19.png)

deleteTapa:
![image](https://user-images.githubusercontent.com/79944367/230725334-90ec49e2-343a-4581-9222-819a1c69356e.png)
after deletion:
![image](https://user-images.githubusercontent.com/79944367/230725577-c83b82fa-602f-418f-a848-2d2d50764d7b.png)
