### ISSUE TITLE
Testing Tapas

### ISSUE THREAD

**Issue by JLDEMIGUEL** [dDevTech/tapas-top-backend#58]
Testear métodos de Resource y Service:
- findAll
- findById
- save
- deleteById

**Comment by edlv2001** [comment]
Pruebas findAll:
![image](https://user-images.githubusercontent.com/79944367/233070337-71e9a2fa-b2e0-4c2f-9410-0bf577301b1f.png)
Response Body
[
    {
        "id": 6,
        "name": "Jamón Ibérico",
        "description": "Paleta de jamón ibérico",
        "type": "roja",
        "country": "mediterranea",
        "establishment": {
            "id": 8,
            "name": "Bar Armando",
            "type": "BAR",
            "createdBy": "prub",
            "createdDate": "2023-04-10T13:51:33.424Z",
            "myCreatedBy": 2051
        },
        "createdBy": "prub",
        "createdDate": "2023-04-03T14:03:56.611803Z",
        "average": 4.0,
        "myCreatedBy": 2051,
        "imageUrl": "https://corsevilla.es/wp-content/uploads/Diferencia-paleta-y-jam%C3%B3n.jpg"
    },
    {
        "id": 10,
        "name": "Aceitunas",
        "description": "Bocado de aceituna gordal con queso de oveja y tomate seco",
        "type": "otro",
        "country": "mediterranea",
        "establishment": {
            "id": 10,
            "name": "Bar el 2D",
            "type": "BAR",
            "createdBy": "prub",
            "createdDate": "2023-04-09T13:51:33.424Z",
            "myCreatedBy": 2051
        },
        "createdBy": "prub",
        "createdDate": "2023-04-12T14:03:56.611Z",
        "average": 5.0,
        "myCreatedBy": 2051,
        "imageUrl": "https://i0.wp.com/pedrochesgastronomia.com/wp-content/uploads/2021/10/Aceituna-gordal-rellena-de-Queso-y-Tomate-800x600.jpg?resize=800%2C600&ssl=1"
    },
    {
        "id": 2201,
        "name": "Patatas bravas2",
        "type": "otro",
        "country": "mediterranea",
        "establishment": {
            "id": 3,
            "name": "Chuka Ramen Bar",
            "type": "RESTAURANTE",
            "createdBy": "1",
            "createdDate": "2023-03-30T16:17:28.279474Z",
            "myCreatedBy": 1
        },
        "createdBy": "admin",
        "createdDate": "2023-04-08T14:00:51.628761Z",
        "lastModifiedBy": "admin",
        "lastModifiedDate": "2023-04-08T14:00:51.628761Z",
        "average": 0.0,
        "myCreatedBy": 1653
    },
    {
        "id": 15,
        "name": "Ensalada de huevo poché",
        "description": "Ensalada de huevo poché con aguacate y langostinos",
        "type": "otro",
        "country": "francesa",
        "establishment": {
            "id": 13,
            "name": "Restaurante Kuche",
            "type": "RESTAURANTE",
            "createdBy": "prub",
            "createdDate": "2023-04-03T13:51:33.424695Z",
            "myCreatedBy": 2051
        },
        "createdBy": "prub",
        "createdDate": "2023-04-03T14:03:56.611803Z",
        "average": 1.0,
        "myCreatedBy": 2051,
        "imageUrl": "https://www.clara.es/medio/2017/04/04/huevo-poche-con-aguacate-y-langostinos_600x900_820811d5.jpg"
    },
    {
        "id": 1,
        "name": "Huevos rotos",
        "description": "Huevos rotos con jamon",
        "type": "otro",
        "country": "mediterranea",
        "establishment": {
            "id": 1,
            "name": "Burguer",
            "type": "RESTAURANTE",
            "createdBy": "1",
            "myCreatedBy": 1
        },
        "createdBy": "1",
        "createdDate": "2023-03-25T00:00:00Z",
        "average": 4.0,
        "myCreatedBy": 1
    },
    {
        "id": 12,
        "name": "Mary Montaña",
        "description": "Rabo de toro glaseado con risotto marinero",
        "type": "roja",
        "country": "otro",
        "establishment": {
            "id": 11,
            "name": "El Perro y la Galleta Malasaña",
            "type": "RESTAURANTE",
            "createdBy": "prub",
            "createdDate": "2023-04-14T13:51:33.424Z",
            "myCreatedBy": 2051
        },
        "createdBy": "prub",
        "createdDate": "2023-04-08T14:03:56.611Z",
        "average": 4.0,
        "myCreatedBy": 2051,
        "imageUrl": "https://elperroylagalleta.com/wp-content/uploads/2016/08/MAR-Y-MONTAN%CC%83A.jpg"
    },
    {
        "id": 5,
        "name": "Chopitos",
        "type": "otro",
        "country": "mediterranea",
        "establishment": {
            "id": 2,
            "name": "Casa Paco",
            "type": "RESTAURANTE",
            "createdBy": "xinru",
            "createdDate": "2023-03-26T00:00:00Z",
            "myCreatedBy": 2051
        },
        "createdBy": "1",
        "createdDate": "2023-03-23T00:00:00Z",
        "average": 2.0,
        "myCreatedBy": 1
    },
    {
        "id": 3,
        "name": "Tosta con jamón",
        "type": "otro",
        "country": "mediterranea",
        "establishment": {
            "id": 2,
            "name": "Casa Paco",
            "type": "RESTAURANTE",
            "createdBy": "xinru",
            "createdDate": "2023-03-26T00:00:00Z",
            "myCreatedBy": 2051
        },
        "createdBy": "1",
        "createdDate": "2023-03-20T00:00:00Z",
        "average": 5.0,
        "myCreatedBy": 1
    },
    {
        "id": 9,
        "name": "Patatas bravas",
        "description": "Patatas en rica salsa hecha a base de tomate con toque justo de jalapeños.",
        "type": "otro",
        "country": "mediterranea",
        "establishment": {
            "id": 9,
            "name": "Lead Bar Madrid",
            "type": "BAR",
            "createdBy": "prub",
            "createdDate": "2023-04-13T13:51:33.424Z",
            "myCreatedBy": 2051
        },
        "createdBy": "prub",
        "createdDate": "2023-04-10T14:03:56.611Z",
        "average": 2.0,
        "myCreatedBy": 2051,
        "imageUrl": "https://www.annarecetasfaciles.com/files/dsc01788.jpg"
    },
    {
        "id": 14,
        "name": "Presa ibérica",
        "description": "Presa ibérica con parmentier de coliflor",
        "type": "roja",
        "country": "mediterranea",
        "establishment": {
            "id": 12,
            "name": "Falling Leaves",
            "type": "RESTAURANTE",
            "createdBy": "prub",
            "createdDate": "2023-04-13T13:51:33.424Z",
            "myCreatedBy": 2051
        },
        "createdBy": "prub",
        "createdDate": "2023-04-14T14:03:56.611Z",
        "average": 4.0,
        "myCreatedBy": 2051,
        "imageUrl": "https://www.recetassinlactosa.com/wp-content/uploads/2018/03/Presa-ib%C3%A9rica-con-parmentier-y-setas-1.jpg"
    },
    {
        "id": 13,
        "name": "Hamburguesa de vaca",
        "description": "Hamburguesa de vaca madurada, mozarella y mahonesa de trufa",
        "type": "roja",
        "country": "mediterranea",
        "establishment": {
            "id": 12,
            "name": "Falling Leaves",
            "type": "RESTAURANTE",
            "createdBy": "prub",
            "createdDate": "2023-04-13T13:51:33.424Z",
            "myCreatedBy": 2051
        },
        "createdBy": "prub",
        "createdDate": "2023-04-09T14:03:56.611Z",
        "average": 3.0,
        "myCreatedBy": 2051,
        "imageUrl": "https://2.bp.blogspot.com/-mO24agnTv0c/WCzDGk83vnI/AAAAAAAAWoA/k3JMPz3VyIwQuFnMLA-5W2G6h_abawhDQCPcB/s1600/Hamburguesa-setas-Persucarhipa.JPG"
    },
    {
        "id": 11,
        "name": "Gyozas",
        "description": "Gyozas de pollo con mayo de yuzu, salsa chili garlic y kumquat confitado",
        "type": "otro",
        "country": "asiatica",
        "establishment": {
            "id": 11,
            "name": "El Perro y la Galleta Malasaña",
            "type": "RESTAURANTE",
            "createdBy": "prub",
            "createdDate": "2023-04-14T13:51:33.424Z",
            "myCreatedBy": 2051
        },
        "createdBy": "prub",
        "createdDate": "2023-04-11T14:03:56.611Z",
        "average": 4.0,
        "myCreatedBy": 2051,
        "imageUrl": "https://chefeel.com/chefgeneralfiles/2021/12/gyozas-2-scaled.jpg"
    },
    {
        "id": 8,
        "name": "Ensaladilla rusa",
        "description": "Tradicional ensalada con un toque especial de la casa.",
        "type": "otro",
        "country": "rusa",
        "establishment": {
            "id": 9,
            "name": "Lead Bar Madrid",
            "type": "BAR",
            "createdBy": "prub",
            "createdDate": "2023-04-13T13:51:33.424Z",
            "myCreatedBy": 2051
        },
        "createdBy": "prub",
        "createdDate": "2023-04-11T14:03:56.611Z",
        "average": 1.0,
        "myCreatedBy": 2051,
        "imageUrl": "https://www.conmuchagula.com/wp-content/uploads/2021/06/ensaladilla-rusa-rianxeitra.jpg"
    },
    {
        "id": 2301,
        "name": "Nachos con guacamole",
        "type": "otro",
        "country": "mexicana",
        "establishment": {
            "id": 25,
            "name": "Bar Jose",
            "type": "BAR",
            "createdBy": "jose",
            "createdDate": "2023-04-09T09:11:44.837485Z",
            "lastModifiedBy": "jose",
            "lastModifiedDate": "2023-04-09T09:11:44.837485Z",
            "myCreatedBy": 1051
        },
        "createdBy": "jose",
        "createdDate": "2023-04-09T09:12:31.437613Z",
        "lastModifiedBy": "jose",
        "lastModifiedDate": "2023-04-09T09:12:31.437613Z",
        "average": 0.0,
        "myCreatedBy": 1051
    },
    {
        "id": 4,
        "name": "Aceitunas",
        "type": "otro",
        "country": "mediterranea",
        "establishment": {
            "id": 2,
            "name": "Casa Paco",
            "type": "RESTAURANTE",
            "createdBy": "xinru",
            "createdDate": "2023-03-26T00:00:00Z",
            "myCreatedBy": 2051
        },
        "createdBy": "1",
        "createdDate": "2023-03-28T00:00:00Z",
        "average": 1.0,
        "myCreatedBy": 1
    },
    {
        "id": 7,
        "name": "Quesos",
        "description": "Tabla de quesos con 5 variedades",
        "type": "leche",
        "country": "mediterranea",
        "establishment": {
            "id": 8,
            "name": "Bar Armando",
            "type": "BAR",
            "createdBy": "prub",
            "createdDate": "2023-04-10T13:51:33.424Z",
            "myCreatedBy": 2051
        },
        "createdBy": "prub",
        "createdDate": "2023-04-03T14:03:56.611803Z",
        "average": 3.0,
        "myCreatedBy": 2051,
        "imageUrl": "https://www.250gramosdequeso.com/wp-content/uploads/2021/12/tabla-de-5-quesos-variados2.jpg"
    },
    {
        "id": 2,
        "name": "Patatas bravas",
        "type": "otro",
        "country": "mediterranea",
        "establishment": {
            "id": 2,
            "name": "Casa Paco",
            "type": "RESTAURANTE",
            "createdBy": "xinru",
            "createdDate": "2023-03-26T00:00:00Z",
            "myCreatedBy": 2051
        },
        "createdBy": "1",
        "createdDate": "2023-03-29T00:00:00Z",
        "average": 3.0,
        "myCreatedBy": 1
    }
]



Pruebas findById:
Tapa no existente 
![image](https://user-images.githubusercontent.com/79944367/233070529-f13d880c-02f0-4cb0-90f6-09932e637f1a.png)
Tapa existente:
![image](https://user-images.githubusercontent.com/79944367/233070711-9f4f8300-5fb1-4826-b534-49f8ab4d048c.png)

Pruebas save:
Creación:
![image](https://user-images.githubusercontent.com/79944367/233070855-d5f7c76c-ae90-49a5-93cd-7f1a6c730b03.png)
Búsqueda posterior:
![image](https://user-images.githubusercontent.com/79944367/233070977-58d54cfb-9469-45b7-80b0-aa85c0d6e484.png)

Pruebas deleteById:
Borrado:
![image](https://user-images.githubusercontent.com/79944367/233071124-79bbd8b5-5c11-42af-adde-073ef210a42c.png)
Búsqueda posterior:
![image](https://user-images.githubusercontent.com/79944367/233071190-54082842-1035-4f4f-af92-098694f97484.png)
Borrado de tapa no existente:
![image](https://user-images.githubusercontent.com/79944367/233071294-7fae10e5-408e-40f3-accd-6f293877a2ac.png)

**Comment by edlv2001** [comment]
Estas pruebas muestran que TapaResource, TapaService y TapaRepository funcionan correctamente y se integran adecuadamente (y se integran con la bdd exitosamente también).
