### ISSUE TITLE
Añadir/Eliminar favoritos 22/04/2023

### ISSUE THREAD

**Issue by JLDEMIGUEL** [dDevTech/tapas-top-backend#67]
Crear dos rutas en MyUserResource para añadir y eliminar una tapa a favoritos:

POST {{url}}/api/myuser/favourites/{tapaId}
DELETE {{url}}/api/myuser/favourites/{tapaId}

Sacar el usuario del token.
Guardar/Eliminar tapa de favoritos
Verificar que tapa existe al añadir y eliminar. Verificar que tapa es favorito al eliminar

**Comment by jesusfl8** [comment]
![Captura](https://user-images.githubusercontent.com/58309329/233969934-8034cd90-899c-403e-bc6c-17d3135953cd.PNG)
