### ISSUE TITLE
Modificar User 20/03/23

### ISSUE THREAD

**Issue by JLDEMIGUEL** [dDevTech/tapas-top-backend#8]
Crear GenderType enum:
MALE,FEMALE

Añadir a User:
- last_name_2: str
- user_name: str
- Foto: Lob (byte[])
- description: str
- gender: GenderType 
- country: str
- address: Address @onetoone

**Comment by xrhuang-13** [comment]
Todo correcto excepto que no se puede meter la foto (atributo: photo)
